# Generated by Django 4.0.3 on 2022-03-15 22:47

from django.db import migrations, models
import pedia_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=pedia_app.models.filepath)),
            ],
        ),
    ]
