# Generated by Django 4.0.3 on 2022-03-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
