# Generated by Django 4.0.3 on 2022-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0004_remove_matches_team1_remove_matches_team2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='t1_id',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='t2_id',
            new_name='team2',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='tourney_id',
            new_name='tourney',
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.CharField(choices=[('T1', 'Team1'), ('T2', 'Team2'), ('DW', 'Draw'), ('ON', 'Ongoing')], default='ON', max_length=2),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
