# Generated by Django 4.0.3 on 2022-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0005_rename_t1_id_matches_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='is_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
