# Generated by Django 4.0.3 on 2022-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0006_matches_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
