# Generated by Django 4.0.3 on 2022-04-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0007_alter_matches_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ign', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/uploads/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedia_app.teams')),
            ],
        ),
    ]
