# Generated by Django 4.0.3 on 2022-04-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0008_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournies',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournies',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedia_app.teams'),
        ),
    ]
