# Generated by Django 4.0.3 on 2022-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedia_app', '0009_alter_tournies_is_finished_alter_tournies_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
